/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//Import the required rent a car pacckages
package UIP;
import ALP.*;
import DSP.OracleJDBCConnection;


//Import other required packages
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author sradder
 */
public class LogInForm extends javax.swing.JFrame {

    private ArrayList<JFrame> formList;

    /**
     * Creates new form LogIn
     */
    public LogInForm(ArrayList<JFrame> formList) {
        this.formList = formList;
        initComponents();
        formList.add(this);
        //Display the screen at the center of the screen
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        // this.setSize(dim);
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtLoginName = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("User ID");

        jLabel2.setText("Login Password");

        btnLogin.setText("Log In");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Rent-A-Car Welomes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnLogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                        .addComponent(txtLoginName, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLogin)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            // TODO add your handling code here:
            //Check if User exists in the database @ application level
            int userID = Integer.parseInt(txtLoginName.getText().trim());
            String loginPassword = txtPassword.getText().trim();

            Login login = new Login(userID, loginPassword);

            //Find user in the DBMS database
            Connection connection = OracleJDBCConnection.connectDataBase();
            Statement st = null;
            try {
                st = connection.createStatement();
            } catch (SQLException ex) {
                Logger.getLogger(OracleJDBCConnection.class.getName()).log(Level.SEVERE, null, ex);
            }

            String sql = " select * from usertable where UserID = " + Integer.parseInt(txtLoginName.getText().trim());
            sql = sql + " and " + " UPW  = '" + txtPassword.getText().trim() + "'";
            System.out.println(sql);
            ResultSet rs = st.executeQuery(sql);

            //Handle incorrect login
            if (rs.next() == false) {
                System.out.println("Result set is null");
                connection.close();
                JOptionPane.showMessageDialog(null, "Incorrect login, Login Again");

                txtLoginName.setText("");
                txtPassword.setText("");
            } else {
                //open main menu
                JOptionPane.showMessageDialog(null, "User Exists");
                this.setVisible(false);
                for (JFrame frame : formList) {
                    if (frame instanceof MainMenuForm) {
                        frame.setVisible(true);
                        break;

                    }
                }
            }

            //IF user exists open next main menu form
                    //else alert wrong login try egain
                    /*
                     if (UserList.findUser(login)) {
                     JOptionPane.showMessageDialog(null, "User Exists");
                     this.setVisible(false);
                     for (JFrame frame : formList) {
                     if (frame instanceof MainMenuForm) {
                     frame.setVisible(true);
                     break;
                     }
            
                     }
            
                     } else {
                     JOptionPane.showMessageDialog(null, "Incorrect login, Login Again");

                     }
            
                     */
        st.close();       
        }catch (SQLException ex) {
            Logger.getLogger(LogInForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
             * @param args the command line arguments
             */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtLoginName;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
