/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UIP;

import DSP.OracleJDBCConnection;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author H_Abb
 */
public class AddCarForm extends javax.swing.JFrame {
private  ArrayList<JFrame> formList;
    /**
     * Creates new form AddCarForm
     */
    public AddCarForm(ArrayList<JFrame> formList) {
        initComponents();
        this.formList =  formList;
         formList.add(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Heading = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        Brand = new javax.swing.JLabel();
        Model = new javax.swing.JLabel();
        Drive = new javax.swing.JLabel();
        DailyCharge = new javax.swing.JLabel();
        Available = new javax.swing.JLabel();
        Capacity = new javax.swing.JLabel();
        TxtID = new javax.swing.JTextField();
        TxtBrand = new javax.swing.JTextField();
        TxtModel = new javax.swing.JTextField();
        TxtDrive = new javax.swing.JTextField();
        TxtCharge = new javax.swing.JTextField();
        TxtCap = new javax.swing.JTextField();
        YesAvail = new javax.swing.JRadioButton();
        NoAvail = new javax.swing.JRadioButton();
        AddCarBtn = new javax.swing.JButton();
        ClearCarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Heading.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        Heading.setText("Add New Car");

        ID.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ID.setText("ID");

        Brand.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Brand.setText("Brand");

        Model.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Model.setText("Model");

        Drive.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Drive.setText("Drive");

        DailyCharge.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        DailyCharge.setText("Daily Charge");

        Available.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Available.setText("Available");

        Capacity.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Capacity.setText("Capacity");

        TxtID.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        TxtBrand.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        TxtModel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        TxtDrive.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        TxtCharge.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        TxtCap.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        YesAvail.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        YesAvail.setText("Yes");

        NoAvail.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        NoAvail.setText("No");

        AddCarBtn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        AddCarBtn.setText("Add Car");
        AddCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCarBtnAction(evt);
            }
        });

        ClearCarBtn.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ClearCarBtn.setText("Clear");
        ClearCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnAction(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Capacity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtCap, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ID)
                                    .addComponent(Brand)
                                    .addComponent(Model)
                                    .addComponent(Drive))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtDrive, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtID, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(AddCarBtn)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(DailyCharge)
                                        .addComponent(Available)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(YesAvail)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(NoAvail))
                                            .addComponent(TxtCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(139, 139, 139)
                                        .addComponent(ClearCarBtn)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(179, 179, 179)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(Heading)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID)
                    .addComponent(TxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Brand)
                    .addComponent(TxtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Model)
                    .addComponent(TxtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Drive)
                    .addComponent(TxtDrive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DailyCharge)
                    .addComponent(TxtCharge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Available)
                    .addComponent(YesAvail)
                    .addComponent(NoAvail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Capacity)
                    .addComponent(TxtCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddCarBtn)
                    .addComponent(ClearCarBtn))
                .addGap(83, 83, 83))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearBtnAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnAction
        // TODO add your handling code here:
        TxtID.setText("");
        TxtBrand.setText("");
        TxtModel.setText("");
        TxtCharge.setText("");
        TxtCap.setText("");
        TxtDrive.setText("");
        
    }//GEN-LAST:event_clearBtnAction

    private void AddCarBtnAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCarBtnAction
        // TODO add your handling code here:
        String id = TxtID.getText();
        String brand = TxtBrand.getText();
        String model = TxtModel.getText();
        String drive = TxtDrive.getText();
        String charge = TxtCharge.getText();
        String capacity = TxtCap.getText();
        String available=YesAvail.isSelected()?"y":"n";
        int intID = Integer.parseInt(id.trim());
        int intModel = Integer.parseInt(model.trim());
        int intDrive = Integer.parseInt(drive.trim());
        double doubleCharge = Double.parseDouble(charge.trim());
        double doubleCap = Double.parseDouble(capacity.trim());
        String sql = "Insert into car values(";
        sql=sql+ intID ;
        sql = sql + ",'" + brand +"'"  ;
        sql = sql + "," + intModel +""  ;
        sql = sql + "," + intDrive ;
        sql = sql + "," + doubleCharge ;
        sql = sql + ",'"+ available + "'";
        sql = sql + "," + doubleCap +")";
        System.out.println(sql);
        Connection conn = OracleJDBCConnection.connectDataBase();
        Statement st = null;
            try {
                st = conn.createStatement();
            } catch (SQLException ex) {
                Logger.getLogger(OracleJDBCConnection.class.getName()).log(Level.SEVERE, null, ex);
            }
        try {
            st.executeQuery(sql);
            st.executeQuery("commit");
            JOptionPane.showMessageDialog(null, "Car Added");
                this.setVisible(false);
                for (JFrame frame : formList) {
                    if (frame instanceof MainMenuForm) {
                        frame.setVisible(true);
                        break;

                    }
                }
        } catch (SQLException ex) {
            Logger.getLogger(AddUserForm.class.getName()).log(Level.SEVERE, null, ex);
        }
     try {
         st.close();
     } catch (SQLException ex) {
         Logger.getLogger(AddUserForm.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_AddCarBtnAction


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCarBtn;
    private javax.swing.JLabel Available;
    private javax.swing.JLabel Brand;
    private javax.swing.JLabel Capacity;
    private javax.swing.JButton ClearCarBtn;
    private javax.swing.JLabel DailyCharge;
    private javax.swing.JLabel Drive;
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel Model;
    private javax.swing.JRadioButton NoAvail;
    private javax.swing.JTextField TxtBrand;
    private javax.swing.JTextField TxtCap;
    private javax.swing.JTextField TxtCharge;
    private javax.swing.JTextField TxtDrive;
    private javax.swing.JTextField TxtID;
    private javax.swing.JTextField TxtModel;
    private javax.swing.JRadioButton YesAvail;
    private javax.swing.ButtonGroup buttonGroup1;
    // End of variables declaration//GEN-END:variables
}
